name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nu-stocks"
          heroku_email: "renansouza-dev@protonmail.com"
          healthcheck: "https://nu-stocks.herokuapp.com/health"
          checkstring: "ok"
          delay: 5